version: "3"

tasks:
  install:
    desc: Install production dependencies
    cmds:
      - uv sync

  dev:
    desc: Install all dependencies including dev
    cmds:
      - uv sync --all-extras

  lint:
    desc: Run linter
    cmds:
      - uv run ruff check src tests

  lint-fix:
    desc: Run linter with auto-fix
    cmds:
      - uv run ruff check --fix src tests

  format:
    desc: Format code
    cmds:
      - uv run ruff format src tests

  format-check:
    desc: Check formatting without making changes
    cmds:
      - uv run ruff format --check src tests

  typecheck:
    desc: Run type checking
    cmds:
      - uv run pyright

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  test-cov:
    desc: Run tests with coverage report
    cmds:
      - uv run pytest --cov=italian_anki --cov-report=term-missing

  check:
    desc: Run all checks (format, lint, typecheck, test)
    cmds:
      - task: format-check
      - task: lint
      - task: typecheck
      - task: test

  pre-commit-install:
    desc: Install pre-commit hooks
    cmds:
      - uv run pre-commit install

  pre-commit-run:
    desc: Run pre-commit on all files
    cmds:
      - uv run pre-commit run --all-files

  import-wiktextract:
    desc: Import Wiktextract data into database
    cmds:
      - uv run italian-anki import-wiktextract {{.CLI_ARGS}}

  enrich-formof:
    desc: Enrich forms with register labels from form-of entries
    cmds:
      - uv run italian-anki enrich-formof {{.CLI_ARGS}}

  import-morphit:
    desc: Enrich forms with real Italian spelling from Morph-it!
    cmds:
      - uv run italian-anki import-morphit {{.CLI_ARGS}}

  import-itwac:
    desc: Import frequency data from ItWaC corpus
    cmds:
      - uv run italian-anki import-itwac {{.CLI_ARGS}}

  import-tatoeba:
    desc: Import Tatoeba sentences and link to verbs
    cmds:
      - uv run italian-anki import-tatoeba {{.CLI_ARGS}}

  import-all:
    desc: Run full import pipeline for a POS (pass --pos=verb|noun|adjective)
    cmds:
      - task: import-wiktextract
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
      - task: enrich-formof
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
      - task: import-morphit
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
      - task: import-itwac
        vars: { CLI_ARGS: "{{.CLI_ARGS}}" }
      - task: import-tatoeba
        vars: { CLI_ARGS: "" }  # tatoeba links to all lemmas, no POS filter

  download-wiktextract:
    desc: Download Wiktextract Italian dictionary
    cmds:
      - uv run italian-anki download-wiktextract {{.CLI_ARGS}}

  download-morphit:
    desc: Download Morph-it! morphological lexicon
    cmds:
      - uv run italian-anki download-morphit {{.CLI_ARGS}}

  download-itwac:
    desc: Download ItWaC frequency lists
    cmds:
      - uv run italian-anki download-itwac {{.CLI_ARGS}}

  download-tatoeba:
    desc: Download Tatoeba sentences and links
    cmds:
      - uv run italian-anki download-tatoeba {{.CLI_ARGS}}

  download-all:
    desc: Download all data sources
    cmds:
      - uv run italian-anki download-all {{.CLI_ARGS}}
