version: "3"

tasks:
  install:
    desc: Install production dependencies
    cmds:
      - uv sync

  dev:
    desc: Install all dependencies including dev
    cmds:
      - uv sync --all-extras

  lint:
    desc: Run linter
    cmds:
      - uv run ruff check src tests

  lint-fix:
    desc: Run linter with auto-fix
    cmds:
      - uv run ruff check --fix src tests

  format:
    desc: Format code
    cmds:
      - uv run ruff format src tests

  format-check:
    desc: Check formatting without making changes
    cmds:
      - uv run ruff format --check src tests

  typecheck:
    desc: Run type checking
    cmds:
      - uv run pyright

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  test-cov:
    desc: Run tests with coverage report
    cmds:
      - uv run pytest --cov=italian_anki --cov-report=term-missing

  check:
    desc: Run all checks (format, lint, typecheck, test)
    cmds:
      - task: format-check
      - task: lint
      - task: typecheck
      - task: test

  pre-commit-install:
    desc: Install pre-commit hooks
    cmds:
      - uv run pre-commit install

  pre-commit-run:
    desc: Run pre-commit on all files
    cmds:
      - uv run pre-commit run --all-files

  import-wiktextract:
    desc: Import Wiktextract data into database
    cmds:
      - uv run italian-anki import-wiktextract {{if .POS}}--pos {{.POS}}{{end}}

  enrich-formof:
    desc: Enrich forms with register labels from form-of entries
    cmds:
      - uv run italian-anki enrich-formof {{if .POS}}--pos {{.POS}}{{end}}

  import-morphit:
    desc: Enrich forms with real Italian spelling from Morph-it!
    cmds:
      - uv run italian-anki import-morphit {{if .POS}}--pos {{.POS}}{{end}}

  import-itwac:
    desc: Import frequency data from ItWaC corpus
    cmds:
      - uv run italian-anki import-itwac {{if .POS}}--pos {{.POS}}{{end}}

  import-tatoeba:
    desc: Import Tatoeba sentences and link to verbs
    cmds:
      - uv run italian-anki import-tatoeba

  import-all:
    desc: Run full import pipeline
    cmds:
      - uv run italian-anki import-all

  stats:
    desc: Show database statistics
    cmds:
      - uv run italian-anki stats

  verify-db:
    desc: Verify database integrity and consistency
    cmds:
      - uv run italian-anki verify {{if .VERBOSE}}-v{{end}}

  download-wiktextract:
    desc: Download Wiktextract Italian dictionary
    cmds:
      - uv run italian-anki download-wiktextract {{if .FORCE}}--force{{end}}

  download-morphit:
    desc: Download Morph-it! morphological lexicon
    cmds:
      - uv run italian-anki download-morphit {{if .FORCE}}--force{{end}}

  download-itwac:
    desc: Download ItWaC frequency lists
    cmds:
      - uv run italian-anki download-itwac {{if .FORCE}}--force{{end}}

  download-tatoeba:
    desc: Download Tatoeba sentences and links
    cmds:
      - uv run italian-anki download-tatoeba {{if .FORCE}}--force{{end}}

  download-all:
    desc: Download all data sources
    cmds:
      - uv run italian-anki download-all {{if .FORCE}}--force{{end}}
